### ISSUE TITLE
Went to extend a built in criteria.

### ISSUE THREAD

**Issue by bweston92** [anlutro/laravel-repository#14]
I was going to make my criteria that searches multiple columns extend SearchCriteria how-ever I believe the `where` should be an `orWhere`. Please tell me if this is not the case so I can proceed to use it.

https://github.com/anlutro/laravel-repository/blob/master/src/Criteria/SearchCriteria.php#L46

**Comment by anlutro** [comment]
I think you're right, but it being part of a public API now I can't really change it.

I'll add a third constructor argument to determine if the behaviour should be AND or OR, but really I recommend you write the criteria classes yourself to gain full control over all behaviours. The existing ones are really just meant as examples or to help people get started.

**Comment by bweston92** [comment]
Ok, that's fine. Thanks.

—
