### ISSUE TITLE
Method update always return a boolean

### ISSUE THREAD

**Issue by DarKDinDoN** [anlutro/laravel-repository#17]
Hello,

Thank you for sharing this package that saves us a lot of time.

I'm wondering why the update method always returns a boolean ?

Here is an example : 

```php
$user = $this->userRepository->findByAttributes(['email' => \Input::get('email')]);
$user = $this->userRepository->update($user, ['reset_token' => 'SomeUniqueId']);

// Then I could send the updated user to a Mailer Service or a Notification Service
// or even raise an event to do the job
```

Since the update method doesn't return an Eloquent instance when the operation succeed, how can I retreive the updated model instance ?

Thanks

**Comment by anlutro** [comment]
```php
$user = $this->userRepository->findByAttributes(['email' => \Input::get('email')]);
$this->userRepository->update($user, ['reset_token' => 'SomeUniqueId']);
// $user is now updated
```

**Comment by anlutro** [comment]
I can add that the reason for this is that objects are always passed by reference in PHP. When you pass the `$user` variable to the `update()` method and the `update()` method does `$model->fill(..)` and so on, it's updating the exact same object/instance that the `$user` variable is pointing to.

This is unlike how arrays work, where whenever you pass an array to a method/function, a copy of the array is being made, and any changes to the array never leaves the scope of the method/function.

**Comment by DarKDinDoN** [comment]
I'm confused and I thought my model wasn't changing after an update.

But you are right (and this was a  simple one ...).

Actually, It seems that the property is null before an update (which is normal) and contains an empty array after. That's weird : 

```php
// Before update :
"reset_token":null

// After update :
"reset_token":{}
```

But the model is correctly persisted in the dtb.

Any idea what i'm doing wrong (again) ?

**Comment by anlutro** [comment]
That's more difficult to say, you'll probably have to debug it on your own. I can't think of anything in this library that could cause something like that.

Do a `var_dump` on the array you're passing to `userRepository->update` and make sure everything there looks alright. Also check if you have a `setResetTokenAttribute` method on your model class, and possibly if there could be model events changing the reset token afterwards.

**Comment by DarKDinDoN** [comment]
Ok, found it.

I'm using the Rhumsaa\Uuid package.
I thought Uuid::uuid4() returned a string, but it doesn't.

Thank you for your time :)
