### ISSUE TITLE
Criteria implementations.

### ISSUE THREAD

**Issue by bweston92** [anlutro/laravel-repository#18]
Is there any convenient way to write criteria for multiple repository implementations?

Repository implementations could by Doctrine, RESTful service, XML file reader etc but of course the criteria are only designed for Illuminate's query builder.

The reason I'm using this package is to be able to replace repositories with multiple implementations if necessary. 

Another suggestion would be to make methods on the repository interface and the Eloquent implementation it self can use the Eloquent criteria.

What would you do?

**Comment by anlutro** [comment]
If you want to make sure that the repository can easily be switched out by another implementation later on I'd say it's very important not to use criteria as part of the repository's public interface.

I.e. it's OK for the repository to have a method that creates a criteria object and pushes it onto itself, but it's not OK for a controller (or any other class) to create a criteria object and push it onto the repository.

This might mean that you get really long method names (like `getIncompleteBetweenDatesForCustomerIdAndProjectId`), but you'll have a clearly defined interface that isn't tightly coupled to any library or persistence layer.

**Comment by bweston92** [comment]
Thanks.

**Comment by anlutro** [comment]
Doctrine does a far better job at this, their criteria are just a collection of expressions that are completely database-agnostic. I assume their repository implementation then parses the criteria object and converts it at run-time into SQL (or DQL or calls to the query builder). I'm not even going to attempt replicating that though.
