### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by bweston92** [anlutro/laravel-repository#19]
Ok so pagination works from HTTP requests but from command line there is no way to skip?

I did try adding a `skip` method and in `beforeQuery` call skip on the query object but no look.

Any ideas on achieving this? This means by daemon/cli-app could potentially load a lot of data at once into RAM.

**Comment by anlutro** [comment]
I think you can call `Paginator::setCurrentPage($page)` to fake the page.

**Comment by bweston92** [comment]
Hmmm so inject the Paginator instance. I'm not to keen but if it works.

**Comment by anlutro** [comment]
That being said I don't know why `$query->limit($x)->offset($y)` in `beforeQuery` shouldn't work, if that is an option.

**Comment by bweston92** [comment]
That would be a nice option but no, https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Query/Builder.php#L1409

**Comment by anlutro** [comment]
I meant omitting the `paginate()` call altogether when you're in a CLI context.
