### ISSUE TITLE
Polymorphic relationships.

### ISSUE THREAD

**Issue by bweston92** [anlutro/laravel-repository#21]
When using polymorphic relationships how is it best handled in repository pattern?

Idea 1:
```
class B {
    public function __construct(BModel $bM, BValidator $bV, A $a);

    public function create()
    {
        $m = parent::create();
        $this->a->create(['related_id' => $m->getKey(), 'related_type' => get_class($m)]);
        return $m;
    }
}
```

Idea 2: Have the A repository create the related models too.

Which would be best?

**Comment by anlutro** [comment]
How does polymorphic relationships differ from regular relationships in this context?

What I've usually done is attach the related models in `beforeSave` (for BelongsTo relationships) or `afterSave` (for HasMany/ManyToMany relationships).

If your related model creation logic is more than super simple, you might want to create a wrapper class around your two repositories and handle the relationship logic there.

For example, here's some code from `class WastageManager` that creates a wastage and attaches the current department's items to that wastage:

```php
	public function create(array $attributes)
	{
		$this->wastage->toggleExceptions(true);
		$this->items->toggleExceptions(true);

		$result = $this->transaction(function() use($attributes)
		{
			$wastage = $this->wastage->create($attributes);

			$products = $this->department->products;

			$this->items->syncNewWastageItems($wastage, $products, $attributes['items']);

			return $wastage;
		});

		return $result;
	}
```

The `syncNewWastageItems` method can be found [here](https://github.com/anlutro/laravel-repository/blob/5a7ae6cd5433195f3c34a46e877d76bc19ab00d9/examples/RealWorldExample.php#L78).

**Comment by bweston92** [comment]
Thanks.
